### ISSUE TITLE
Issues with video feed

### ISSUE THREAD

**Issue by MisterSyn** [Ruslan-B/AR.Drone#11]
Hi,

I have managed to get the code working with my AR Drone, controls and data streams work fine, however I am having issues with receiving video data from the drone; the pictureBox stays grey. My thought is that this could be partly due to FFMPEG libraries. How exactly should I be compiling the FFMPEG solution to work with the program?

Thanks.

**Comment by Ruslan-B** [comment]
Hi there, well it is pretty common issue you need to clone repo using git with linked submodule or download exactly this version of ffmpeg.autogen (it includes all binaries for windows but you need to specify search path or copy them next to demo app exe manually): 
https://github.com/Ruslan-B/FFmpeg.AutoGen/tree/7e001dde3acaad70ed188b75e686f23574f81388

**Comment by MisterSyn** [comment]
I checked out the repo with the linked submodule as suggested however the picturebox container remains grey. I will try again this Tuesday

**Comment by Ruslan-B** [comment]
can we close it?
