### ISSUE TITLE
Multiple Ar Drones

### ISSUE THREAD

**Issue by Geaper** [Ruslan-B/AR.Drone#12]
Hello. I cant get navigationdata nor video stream from 2 ar drones.

Do you know how to do it?

I tried Like this:

              //Novo Cliente
            _droneClient = new DroneClient("192.168.1." + ip1);
            _droneClient.NavigationPacketAcquired += OnNavigationPacketAcquired;
            _droneClient.VideoPacketAcquired += OnVideoPacketAcquired;
            _droneClient.NavigationDataAcquired += data => _navigationData = data;

            //Novo Cliente
            _droneClient2 = new DroneClient("192.168.1." + ip2);
            _droneClient2.NavigationPacketAcquired += OnNavigationPacketAcquired2;
            _droneClient2.VideoPacketAcquired += OnVideoPacketAcquired2;
            _droneClient2.NavigationDataAcquired += data2 => _navigationData2 = data2;`

**Comment by Ruslan-B** [comment]
Hi, I'm not supporting this project any more.
However, connecting two drones to single wifi network not so trivial and (not this library concern) if you can't ping them both then you did something wrong during drone wifi and/ip configuration.

Cheers,
Ruslan

**Comment by Geaper** [comment]
I can ping them. Everything Works except the code. Just tell me if for exemple I have 10 AR.Drones I have to create 10x this code? I need to create multiple  OnNavigationPacketAcquired, OnVideoPacketAcquired, navigationData,etc..??
 
Do you have any code exemple of 2 or more drones conected?
 
 
> ` //Novo Cliente
> _droneClient = new DroneClient("192.168.1." + ip1);
> _droneClient.NavigationPacketAcquired += OnNavigationPacketAcquired;
> _droneClient.VideoPacketAcquired += OnVideoPacketAcquired;
> _droneClient.NavigationDataAcquired += data => _navigationData = data;
> 
> //Novo Cliente
> _droneClient2 = new DroneClient("192.168.1." + ip2);
> _droneClient2.NavigationPacketAcquired += OnNavigationPacketAcquired2;
> _droneClient2.VideoPacketAcquired += OnVideoPacketAcquired2;
> _droneClient2.NavigationDataAcquired += data2 => _navigationData2 = data2;`
 
 
Repeat ….
 
Thank you

**Comment by Ruslan-B** [comment]
Newer tested myself, but some people succeed afaik. There are no statics in code, the rest is plain udp/tcp networking with specific network address thus should work. With respect how many handlers you need to create it depends, for video for example you need dedicated decoders. I would advice to test navdata part without video, one by one, then together.

Cheers,
Ruslan
