### ISSUE TITLE
Multiple Ar Drones

### ISSUE THREAD

**Issue by Geaper** [Ruslan-B/AR.Drone#13]
Hello again Ruslan.

I managed to make both work but the only problem is that I can only send commands one at the time.

I have to _droneClient.Stop() in order to send commands to _droneClient2 and vise-versa. Isnt there any way u can help me solve this? U created this code, must be really easy for you. :(

**Comment by Ruslan-B** [comment]
Ok just some google magic:
https://github.com/AutonomyLab/ardrone_autonomy/issues/56#issuecomment-16648716
Socket is already occupied. 
But you need to fix it yourself - how I have no clue but can assume in NavdataAcquisition class.

Start your application in debug and check debug output - most likely you will find some network exceptions happing during connection.

Cheers,
Ruslan

**Comment by Ruslan-B** [comment]
P.S. It is not easy.

**Comment by Geaper** [comment]
Maybe I can pay you to solve me this problem? :/ do you have paypal?

**Comment by Ruslan-B** [comment]
Haha funny. How do you imagine this? In order to do so I need at least two drones.

Cheers,
Ruslan

**Comment by Geaper** [comment]
:( if u look at the code u dont know how to resolve it? Even if I open 2 different applications it doesnt work. It only works if I use 2 different PCs connected to the same router. So it's 100% port problem.

**Comment by Ruslan-B** [comment]
oh...you terrible, read about UDP sockets, they are none sharable resources.

**Comment by Geaper** [comment]
it's very hard? :( so my only change is to use ROS?

**Comment by Geaper** [comment]
Don't you think it's very strange that the video and navdata works perfectly but only takeoff, land etc commands dont work on the same PC?

**Comment by Ruslan-B** [comment]
it requires drones you do have and (small?) fix in NavdataAcquisition class with respect to UdpClient.

**Comment by Ruslan-B** [comment]
may be you will read thoroughly link I sent?

**Comment by Geaper** [comment]
I have to admit I am not the best programmer ^^ I ask kindly for ur help and time. The best I can do is pay you for ur time or give you some PC games if u play ;)

**Comment by Geaper** [comment]
I have 2 drones if u want we can use teamviewer.

**Comment by Geaper** [comment]
OMGGGGGGGGGGGGGGGGGGGGGG IT'S WORKINGGGGGGGGGGGGGGG

**Comment by Geaper** [comment]
OMG IM CRYING

**Comment by Geaper** [comment]
I JUST DELETED ONE WORD AND IT STARTED WORKING!!! IM BEST PROGRAMMER EUROPE!

**Comment by Geaper** [comment]
var udpClient = new UdpClient(CommandPort)) to var udpClient = new UdpClient())

**Comment by Geaper** [comment]
Who would have though that Visual Studio showed you debug errors.

**Comment by Ruslan-B** [comment]
Better learn how to. Maybe in few weeks I can take a look, I'm on vacation right now only with my phone on me. Good luck then.

**Comment by Ruslan-B** [comment]
Nice.
