### ISSUE TITLE
HD Video Stream

### ISSUE THREAD

**Issue by ptrkds** [Ruslan-B/AR.Drone#14]
Can you say some information about the HD video stream, please?

I can't even find the solution to have HD video stream with this SDK. 
I tried some things.. But nothing happened with different Bitrates (and h264 auto resize codec type) or with different CodecTypes.

**Comment by Ruslan-B** [comment]
You need to enable multi-configuration mode: https://github.com/Ruslan-B/AR.Drone/wiki/How-to-do.
